version: 1
group: policy
total_dim: 72
terms:
- name: base_ang_vel
  func: base_ang_vel
  shape:
  - 3
  dim: 3
  clip: null
  params: null
- name: generated_commands
  func: generated_commands
  shape:
  - 3
  dim: 3
  clip: null
  params: null
- name: joint_pos_rel
  func: joint_pos_rel
  shape:
  - 21
  dim: 21
  clip: null
  params:
    joint_order:
    - shin_l_active
    - shin_r_active
    - shoulder_l_roll
    - shoulder_r_roll
    - thigh_l_active
    - thigh_r_active
    - ankle_l_roll
    - ankle_l_yaw
    - ankle_r_roll
    - ankle_r_yaw
    - chest
    - elbow_l_front
    - elbow_l_rear
    - elbow_r_front
    - elbow_r_rear
    - hip_l_pitch
    - hip_l_roll
    - hip_r_pitch
    - hip_r_roll
    - shoulder_l_pitch
    - shoulder_r_pitch
    offsets:
    - 0.0
    - 0.0
    - -1.4311699867248535
    - 1.4311699867248535
    - 0.0
    - 0.0
    - -0.1745329201221466
    - 0.0
    - 0.1745329201221466
    - 0.0
    - 0.0
    - -1.5700000524520874
    - -1.5700000524520874
    - -1.5700000524520874
    - -1.5700000524520874
    - 0.0
    - 0.1745329201221466
    - 0.0
    - -0.1745329201221466
    - -1.5700000524520874
    - -1.5700000524520874
    relative: true
- name: joint_vel_rel
  func: joint_vel_rel
  shape:
  - 21
  dim: 21
  clip: null
  params:
    joint_order:
    - shin_l_active
    - shin_r_active
    - shoulder_l_roll
    - shoulder_r_roll
    - thigh_l_active
    - thigh_r_active
    - ankle_l_roll
    - ankle_l_yaw
    - ankle_r_roll
    - ankle_r_yaw
    - chest
    - elbow_l_front
    - elbow_l_rear
    - elbow_r_front
    - elbow_r_rear
    - hip_l_pitch
    - hip_l_roll
    - hip_r_pitch
    - hip_r_roll
    - shoulder_l_pitch
    - shoulder_r_pitch
    offsets:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    relative: true
- name: last_action
  func: last_action
  shape:
  - 21
  dim: 21
  clip: null
  params: null
- name: base_lin_acc_sens
  func: base_lin_acc_sens
  shape:
  - 3
  dim: 3
  clip: null
  params: null
source:
  type: isaaclab
  file: exported/IO_descriptors.yaml
