controller_manager:
  ros__parameters:
    update_rate: 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_group_position_pid_controller:
      type: pid_controller/PidController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - chest
      - shoulder_r_pitch
      - shoulder_r_roll
      - elbow_r_front
      - elbow_r_rear
      - shoulder_l_pitch
      - shoulder_l_roll
      - elbow_l_front
      - elbow_l_rear
      - hip_r_roll
      - hip_r_pitch
      - thigh_r_active
      - shin_r_active
      - ankle_r_roll
      - ankle_r_yaw
      - hip_l_roll
      - hip_l_pitch
      - thigh_l_active
      - shin_l_active
      - ankle_l_roll
      - ankle_l_yaw

joint_group_position_pid_controller:
  ros__parameters:
    command_interface: effort
    reference_and_state_interfaces:
      - position
    dof_names:
      - chest
      - shoulder_r_pitch
      - shoulder_r_roll
      - elbow_r_front
      - elbow_r_rear
      - shoulder_l_pitch
      - shoulder_l_roll
      - elbow_l_front
      - elbow_l_rear
      - hip_r_roll
      - hip_r_pitch
      - thigh_r_active
      - shin_r_active
      - ankle_r_roll
      - ankle_r_yaw
      - hip_l_roll
      - hip_l_pitch
      - thigh_l_active
      - shin_l_active
      - ankle_l_roll
      - ankle_l_yaw
    use_external_measured_states: false
    gains:
      chest:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      shoulder_r_pitch:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      shoulder_r_roll:
        p: 42.41
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      elbow_r_front:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      elbow_r_rear:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      shoulder_l_pitch:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      shoulder_l_roll:
        p: 42.41
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      elbow_l_front:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      elbow_l_rear:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      hip_r_roll:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      hip_r_pitch:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      thigh_r_active:
        p: 42.41
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      shin_r_active:
        p: 42.41
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      ankle_r_roll:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      ankle_r_yaw:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      hip_l_roll:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      hip_l_pitch:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      thigh_l_active:
        p: 42.41
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      shin_l_active:
        p: 42.41
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      ankle_l_roll:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2

      ankle_l_yaw:
        p: 16.62
        i: 0.0
        d: 0.0
        antiwindup: false
        i_clamp_max: 0.2
        i_clamp_min: -0.2
