from pathlib import Path

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction, ExecuteProcess
from launch.substitutions import LaunchConfiguration
from launch_ros.substitutions import FindPackageShare


def _setup(context, *args, **kwargs):
    pkg_share = Path(FindPackageShare("kuroko_isaac_config_generator").perform(context))

    input_usda = LaunchConfiguration("input_usda").perform(context)
    input_sdf = LaunchConfiguration("input_sdf").perform(context)
    output_usda = LaunchConfiguration("output_usda").perform(context)
    exclude_yaml = LaunchConfiguration("exclude_yaml").perform(context)

    if not exclude_yaml:
        exclude_yaml = str(pkg_share / "config" / "exclude_from_articulation.yaml")

    script = str(pkg_share / "scripts" / "usda_for_isaaclab.py")

    cmd = [
        "python3",
        script,
        "--input_usda",
        input_usda,
        "--input_sdf",
        input_sdf,
        "--output_usda",
        output_usda,
        "--exclude_yaml",
        exclude_yaml,
    ]

    return [ExecuteProcess(cmd=cmd, output="screen")]


def generate_launch_description():
    return LaunchDescription(
        [
            DeclareLaunchArgument(
                "input_usda",
                default_value="/tmp/kuroko_usd_out/kuroko.usda",
                description="Input USDA generated by sdf2usd",
            ),
            DeclareLaunchArgument(
                "input_sdf",
                default_value="/tmp/kuroko_usd_out/kuroko.resolved.sdf",
                description="Resolved SDF (use the output of xacro_to_sdf.launch.py)",
            ),
            DeclareLaunchArgument(
                "output_usda",
                default_value="/tmp/kuroko_usd_out/kuroko.isaaclab.usda",
                description="Output USDA edited for Isaac Lab",
            ),
            DeclareLaunchArgument(
                "exclude_yaml",
                default_value="",
                description="YAML listing joint names/patterns to set physics:excludeFromArticulation=1 (empty uses package default)",
            ),
            OpaqueFunction(function=_setup),
        ]
    )
