<?xml version="1.0"?>
<package format="3">
  <name>kuroko_hw_bringup</name>
  <version>0.0.0</version>
  <description>kuroko_hw_bringup package</description>

  <maintainer email="TODO@example.com">TODO</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
